name: led_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  connectivity_plus: ^6.1.3
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  fluttertoast: ^8.2.12
  http: ^1.3.0
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
